import React, { useEffect, useRef, useState } from 'react';
import api from '../../services/api';
import AppShell from '../../components/common/AppShell';

const starters = [
  ['Plan my next study session', 'Build a focused session from my current roadmap.'],
  ['Explain my skill gap', 'Tell me what to learn first and why.'],
  ['Quiz me on my current topic', 'Test my understanding with useful feedback.'],
  ['Help me choose a course', 'Compare the best next resources for my goal.']
];

export default function AIAssistant() {
  const [messages, setMessages] = useState([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [initialLoad, setInitialLoad] = useState(true); const [error, setError] = useState(''); const messagesEndRef = useRef(null);
  useEffect(() => { api.get('/ai/history').then((response) => { const history = response.data?.data; setMessages(Array.isArray(history?.messages) ? history.messages : Array.isArray(history) ? history : []); }).catch(() => {}).finally(() => setInitialLoad(false)); }, []);
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);
  const send = async (value = input) => { const text = value.trim(); if (!text || loading) return; setMessages((current) => [...current, { role: 'user', content: text }]); setInput(''); setLoading(true); setError(''); try { const response = await api.post('/ai/chat', { message: text }); const reply = response.data?.data?.reply || 'I could not prepare a useful answer right now.'; setMessages((current) => [...current, { role: 'assistant', content: reply }]); } catch (requestError) { const backendMessage = requestError.response?.data?.message || ''; setError(backendMessage || 'The mentor is temporarily unavailable. Please try again.'); } finally { setLoading(false); } };
  const clear = async () => { try { await api.delete('/ai/history'); setMessages([]); setError(''); } catch (_error) { setError('Unable to clear this conversation.'); } };
  const copy = (content) => navigator.clipboard?.writeText(content);
  return <AppShell><div className="page-wrap mentor-page"><div className="mentor-header"><div className="mentor-title-wrap"><div className="mentor-mark">CC</div><div><div className="page-eyebrow">CodexCrue Mentor</div><h1 className="page-title">A sharper next step.</h1><p className="page-subtitle">Ask for direction, an explanation, a plan, or a challenge based on your learning context.</p></div></div><div className="mentor-header-actions"><span className="mentor-status"><i /> Context aware</span><button className="btn btn-ghost" onClick={clear} disabled={!messages.length}>Clear conversation</button></div></div><div className="mentor-shell card"><div className="mentor-messages">{initialLoad ? <div className="mentor-empty">Loading your mentor workspace...</div> : messages.length === 0 ? <div className="mentor-welcome"><div className="mentor-welcome-icon">✦</div><h2>What would make your next hour count?</h2><p>Your mentor can use your goal, current skills and roadmap to make the advice practical.</p><div className="mentor-starters">{starters.map(([title, description]) => <button key={title} className="mentor-starter" onClick={() => send(title)}><strong>{title}</strong><span>{description}</span><b>→</b></button>)}</div></div> : messages.map((message, index) => <Message key={index} message={message} onCopy={copy} />)}{loading && <div className="mentor-message assistant"><div className="mentor-avatar">CC</div><div className="mentor-bubble typing"><i /><i /><i /></div></div>}<div ref={messagesEndRef} /></div>{error && <div className="mentor-error">{error}</div>}<form className="mentor-composer" onSubmit={(event) => { event.preventDefault(); send(); }}><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask your mentor anything about your learning..." rows="1" disabled={loading} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send(); } }} /><button className="mentor-send" type="submit" disabled={loading || !input.trim()}>Send <span>↗</span></button></form><div className="mentor-composer-note">Enter to send · Shift + Enter for a new line · Advice is grounded in your saved learner context.</div></div></div></AppShell>;
}

function Message({ message, onCopy }) { const isUser = message.role === 'user' || message.sender === 'user'; return <div className={`mentor-message ${isUser ? 'user' : 'assistant'}`}>{!isUser && <div className="mentor-avatar">CC</div>}<div className="mentor-message-group"><div className="mentor-message-label">{isUser ? 'You' : 'CodexCrue Mentor'}</div><div className="mentor-bubble">{message.content}</div>{!isUser && <button className="mentor-copy" type="button" onClick={() => onCopy(message.content)}>Copy response</button>}</div></div>; }
