import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import AppShell from '../../components/common/AppShell';
import api from '../../services/api';

export default function CourseDetails() {
  const { id } = useParams(); const [course, setCourse] = useState(null); const [progress, setProgress] = useState(null); const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [feedbackSaving, setFeedbackSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.get(`/courses/${id}`), api.get('/progress')]).then(([courseResponse, progressResponse]) => { setCourse(courseResponse.data.data); setProgress((progressResponse.data.data || []).find((item) => item.courseId?._id === id || item.courseId === id) || null); }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load course.')); }, [id]);
  const startLearning = () => { if (course?.sourceUrl) window.open(course.sourceUrl, '_blank', 'noopener,noreferrer'); setMessage('Learning started. Your time and completion will update automatically.'); };
  const sendFeedback = async (event) => { event.preventDefault(); setFeedbackSaving(true); setMessage(''); setError(''); try { await api.post('/feedback', { targetType: 'course', targetId: id, rating: Number(rating), comment }); setMessage('Thanks — your feedback was recorded.'); setRating(0); setComment(''); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to submit feedback.'); } finally { setFeedbackSaving(false); } };
  return <AppShell><div className="page-wrap">{error && !course ? <div className="error-box">{error}</div> : course ? <><Link to="/courses" className="tag">← Back to catalog</Link><div className="hero-panel" style={{ marginTop: 18 }}><div className="eyebrow">{course.category || 'Course'} · {course.difficulty}</div><h1>{course.title}</h1><p>{course.description}</p><div className="course-meta">{course.skills?.map((skill) => <span className="tag" key={skill}>{skill}</span>)}</div><button className="button button-primary" style={{ marginTop: 18 }} onClick={startLearning}>Start learning & track ↗</button></div><div className="grid grid-2" style={{ marginTop: 20 }}><section className="surface surface-pad"><div className="section-title"><div><h2>Course details</h2><p>Progress is calculated from verified study sessions.</p></div></div><div className="list"><div className="list-row"><span>Duration</span><strong>{course.duration}</strong></div><div className="list-row"><span>Instructor</span><strong>{course.instructor}</strong></div><div className="list-row"><span>Current progress</span><strong>{progress?.completionPercentage || 0}%</strong></div><div className="list-row"><span>Time studied</span><strong>{Number(progress?.timeSpentHours || 0).toFixed(1)}h</strong></div></div><div className="progress-track" style={{ marginTop: 16 }}><div className="progress-fill" style={{ width: `${progress?.completionPercentage || 0}%` }} /></div><p className="metric-note" style={{ marginTop: 12 }}>Open the resource and keep learning. CodexCrue updates this automatically from tracked study time—there is no manual percentage control.</p></section><section className="surface surface-pad"><div className="section-title"><div><h2>Share feedback</h2><p>Help improve future recommendations.</p></div></div><form onSubmit={sendFeedback}><div className="field"><label>Rating</label><select className="input" value={rating} onChange={(event) => setRating(event.target.value)} required><option value="">Choose a rating</option><option value="1">1 — Needs work</option><option value="2">2 — Fair</option><option value="3">3 — Good</option><option value="4">4 — Great</option><option value="5">5 — Excellent</option></select></div><div className="field" style={{ marginTop: 14 }}><label>Comment</label><textarea className="input" rows="4" maxLength="2000" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="What helped or could be clearer?" /></div><button className="button button-primary" style={{ marginTop: 16 }} disabled={feedbackSaving}>{feedbackSaving ? 'Sending…' : 'Submit feedback'}</button></form></section></div>{message && <div className="tag" style={{ marginTop: 16 }}>{message}</div>}{error && <div className="error-box" style={{ marginTop: 16 }}>{error}</div>}</> : <div className="surface empty">Loading course…</div>}</div></AppShell>;
}
