import React, { useEffect, useState } from 'react';
import AppShell from '../../components/common/AppShell';
import api from '../../services/api';

export default function Resources() {
  const [resources, setResources] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api.get('/learning-resources/recommended').then((response) => setResources(response.data.data || [])).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load learning resources.')).finally(() => setLoading(false)); }, []);
  return <AppShell><div className="page-wrap"><div className="page-header"><div><div className="eyebrow">Beyond the catalogue</div><h1 className="page-title">Resources picked for your next step.</h1><p className="page-subtitle">Curated learning links matched to your goal, skill gaps, level, and quality signals.</p></div><span className="admin-status-pill"><i /> Quality checked</span></div>{error && <div className="error-box">{error}</div>}{loading ? <div className="surface empty">Finding the best resources for you…</div> : resources.length ? <div className="grid grid-3">{resources.map((resource) => <article className="surface course-card" key={resource._id}><div><div className="course-meta"><span className="tag">{resource.provider}</span><span className="tag navy">{resource.sourceType}</span></div><h3>{resource.title}</h3><p>{resource.description || resource.explanation}</p></div><div><div className="course-meta">{(resource.skills || []).slice(0, 3).map((skill) => <span className="tag" key={skill}>{skill}</span>)}</div><p className="metric-note">{Math.round(resource.score * 100)}% match · {resource.explanation}</p><a className="button button-primary" style={{ display: 'block', marginTop: 16, textAlign: 'center' }} href={resource.url} target="_blank" rel="noreferrer">Open resource ↗</a></div></article>)}</div> : <div className="surface empty"><strong>No external resources yet</strong>Admin needs to import trusted learning resources first.</div>}</div></AppShell>;
}
