const Course = require('../models/Course');

const FREE_PUBLIC_COURSES = [
  { title: 'Responsive Web Design', provider: 'freeCodeCamp', qualityScore: 0.95, sourceUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/', instructor: 'freeCodeCamp', description: 'Free interactive curriculum for HTML, CSS, accessibility, and responsive layouts.', skills: ['HTML', 'CSS', 'Responsive Design'], difficulty: 'Beginner', duration: '300 hours', category: 'Web Development' },
  { title: 'JavaScript Algorithms and Data Structures', provider: 'freeCodeCamp', qualityScore: 0.95, sourceUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/', instructor: 'freeCodeCamp', description: 'Free interactive JavaScript, algorithms, data structures, and programming curriculum.', skills: ['JavaScript', 'Algorithms', 'Data Structures'], difficulty: 'Intermediate', duration: '300 hours', category: 'Web Development' },
  { title: 'Learn Web Development', provider: 'MDN', qualityScore: 0.95, sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development', instructor: 'MDN Web Docs', description: 'Structured free tutorials covering essential front-end development skills.', skills: ['HTML', 'CSS', 'JavaScript', 'Accessibility'], difficulty: 'Beginner', duration: '80 hours', category: 'Web Development' },
  { title: 'Scientific Computing with Python', provider: 'freeCodeCamp', sourceUrl: 'https://www.freecodecamp.org/learn/scientific-computing-with-python/', instructor: 'freeCodeCamp', description: 'Free Python curriculum with projects covering programming and scientific computing.', skills: ['Python', 'Programming'], difficulty: 'Beginner', duration: '300 hours', category: 'Data Science' },
  { title: 'FastAPI Tutorial', provider: 'FastAPI', sourceUrl: 'https://fastapi.tiangolo.com/tutorial/', instructor: 'FastAPI Documentation', description: 'Free official step-by-step tutorial for building APIs with FastAPI.', skills: ['Python', 'FastAPI', 'REST API'], difficulty: 'Intermediate', duration: '20 hours', category: 'Backend Development' },
  { title: 'Python Tutorial', provider: 'Python.org', sourceUrl: 'https://docs.python.org/3/tutorial/', instructor: 'Python Documentation', description: 'Free official Python tutorial for learning the language and standard tools.', skills: ['Python'], difficulty: 'Beginner', duration: '30 hours', category: 'Programming' },
  { title: 'Learn JavaScript Full Course', provider: 'YouTube / freeCodeCamp', sourceUrl: 'https://www.youtube.com/watch?v=PkZNo7MFNFg', instructor: 'freeCodeCamp.org', description: 'Free full-length JavaScript course for beginners on YouTube.', skills: ['JavaScript', 'Programming'], difficulty: 'Beginner', duration: '3.5 hours', category: 'Web Development' },
  { title: 'Learn Python Full Course', provider: 'YouTube / freeCodeCamp', sourceUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw', instructor: 'freeCodeCamp.org', description: 'Free full-length Python course for beginners on YouTube.', skills: ['Python', 'Programming'], difficulty: 'Beginner', duration: '4.5 hours', category: 'Programming' },
  { title: 'Learn React Full Course', provider: 'YouTube / freeCodeCamp', sourceUrl: 'https://www.youtube.com/watch?v=bMknfKXIFA8', instructor: 'freeCodeCamp.org', description: 'Free full-length React course for beginners on YouTube.', skills: ['React', 'JavaScript', 'Frontend'], difficulty: 'Intermediate', duration: '12 hours', category: 'Web Development' }
  ,{ title: 'CS50x: Introduction to Computer Science', provider: 'Harvard CS50', qualityScore: 0.95, sourceUrl: 'https://cs50.harvard.edu/x/', instructor: 'Harvard University', description: 'Free university-level introduction to computer science, algorithms, C, Python, SQL, and web development.', skills: ['Computer Science', 'C', 'Python', 'SQL', 'Algorithms'], difficulty: 'Beginner', duration: '120 hours', category: 'Computer Science' }
  ,{ title: 'CS50P: Introduction to Programming with Python', provider: 'Harvard CS50', qualityScore: 0.95, sourceUrl: 'https://cs50.harvard.edu/python/', instructor: 'Harvard University', description: 'Free course focused on learning programming with Python through problem sets and projects.', skills: ['Python', 'Programming'], difficulty: 'Beginner', duration: '70 hours', category: 'Programming' }
  ,{ title: 'Introduction to Computer Science and Programming in Python', provider: 'MIT OpenCourseWare', qualityScore: 0.95, sourceUrl: 'https://ocw.mit.edu/courses/6-100l-introduction-to-computer-science-and-programming-using-python-fall-2022/', instructor: 'MIT OpenCourseWare', description: 'Free MIT course materials for computational thinking and Python programming.', skills: ['Python', 'Computer Science', 'Algorithms'], difficulty: 'Intermediate', duration: '90 hours', category: 'Computer Science' }
  ,{ title: 'The Odin Project: Full Stack JavaScript', provider: 'The Odin Project', qualityScore: 0.9, sourceUrl: 'https://www.theodinproject.com/paths/full-stack-javascript', instructor: 'The Odin Project', description: 'Free open-source full-stack curriculum built around projects, Git, JavaScript, Node.js, and databases.', skills: ['JavaScript', 'Node.js', 'Git', 'Databases', 'React'], difficulty: 'Intermediate', duration: '400 hours', category: 'Full Stack Development' }
  ,{ title: 'Full Stack Open', provider: 'University of Helsinki', qualityScore: 0.95, sourceUrl: 'https://fullstackopen.com/en/', instructor: 'University of Helsinki', description: 'Free modern web development course covering React, Node.js, GraphQL, TypeScript, testing, and CI/CD.', skills: ['React', 'Node.js', 'TypeScript', 'GraphQL', 'Testing'], difficulty: 'Intermediate', duration: '200 hours', category: 'Full Stack Development' }
  ,{ title: 'Node.js Learn', provider: 'Node.js', qualityScore: 0.95, sourceUrl: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs', instructor: 'Node.js Documentation', description: 'Free official learning material for building server-side applications with Node.js.', skills: ['Node.js', 'JavaScript', 'Backend Development'], difficulty: 'Intermediate', duration: '25 hours', category: 'Backend Development' }
  ,{ title: 'SQLBolt Interactive SQL Lessons', provider: 'SQLBolt', qualityScore: 0.88, sourceUrl: 'https://sqlbolt.com/', instructor: 'SQLBolt', description: 'Free interactive SQL lessons and exercises for querying relational databases.', skills: ['SQL', 'Databases'], difficulty: 'Beginner', duration: '10 hours', category: 'Data' }
  ,{ title: 'Machine Learning Crash Course', provider: 'Google', qualityScore: 0.95, sourceUrl: 'https://developers.google.com/machine-learning/crash-course', instructor: 'Google Developers', description: 'Free practical introduction to machine learning concepts, exercises, and visual explanations.', skills: ['Machine Learning', 'Python', 'Statistics'], difficulty: 'Intermediate', duration: '15 hours', category: 'Machine Learning' }
  ,{ title: 'Kaggle Learn: Python', provider: 'Kaggle', qualityScore: 0.9, sourceUrl: 'https://www.kaggle.com/learn/python', instructor: 'Kaggle', description: 'Free hands-on Python micro-course with browser-based exercises.', skills: ['Python', 'Programming'], difficulty: 'Beginner', duration: '7 hours', category: 'Programming' }
  ,{ title: 'Kaggle Learn: Intro to Machine Learning', provider: 'Kaggle', qualityScore: 0.9, sourceUrl: 'https://www.kaggle.com/learn/intro-to-machine-learning', instructor: 'Kaggle', description: 'Free hands-on introduction to machine learning models and validation.', skills: ['Machine Learning', 'Python', 'Scikit-Learn'], difficulty: 'Intermediate', duration: '8 hours', category: 'Machine Learning' }
  ,{ title: 'Docker Getting Started', provider: 'Docker', qualityScore: 0.95, sourceUrl: 'https://docs.docker.com/get-started/', instructor: 'Docker Documentation', description: 'Free official guide to containers, images, Dockerfiles, and deployment basics.', skills: ['Docker', 'DevOps', 'Deployment'], difficulty: 'Intermediate', duration: '12 hours', category: 'DevOps' }
  ,{ title: 'Git and GitHub for Beginners', provider: 'YouTube / Traversy Media', qualityScore: 0.8, sourceUrl: 'https://www.youtube.com/watch?v=SWYqp7iY_Tc', instructor: 'Traversy Media', description: 'Free practical Git and GitHub course covering repositories, branches, and collaboration.', skills: ['Git', 'GitHub', 'Collaboration'], difficulty: 'Beginner', duration: '1.5 hours', category: 'Developer Tools' }
  ,{ title: 'React Course for Beginners', provider: 'YouTube / Programming with Mosh', qualityScore: 0.8, sourceUrl: 'https://www.youtube.com/watch?v=SqcY0GlETPk', instructor: 'Programming with Mosh', description: 'Free React fundamentals course covering components, hooks, state, and practical UI building.', skills: ['React', 'JavaScript', 'Frontend'], difficulty: 'Beginner', duration: '2.5 hours', category: 'Web Development' }
  ,{ title: 'Python for Everybody', provider: 'University of Michigan', qualityScore: 0.9, sourceUrl: 'https://www.py4e.com/lessons', instructor: 'Charles Severance', description: 'Free open course materials for Python programming and data handling.', skills: ['Python', 'Programming', 'Data'], difficulty: 'Beginner', duration: '40 hours', category: 'Programming' }
  ,{ title: 'Python Tutorial in Hindi', provider: 'YouTube / CodeWithHarry', qualityScore: 0.82, sourceUrl: 'https://www.youtube.com/watch?v=gfDE2a7MKjA', instructor: 'CodeWithHarry', description: 'Hindi video course for Python basics, programming concepts, and practical examples.', skills: ['Python', 'Programming'], difficulty: 'Beginner', duration: '11 hours', category: 'Programming', language: 'hi', contentType: 'video' }
  ,{ title: '100 Days of Code Python - Hindi', provider: 'YouTube / CodeWithHarry', qualityScore: 0.82, sourceUrl: 'https://www.youtube.com/watch?v=7wnove7K-ZQ', instructor: 'CodeWithHarry', description: 'Hindi-first Python learning series with daily practice and projects.', skills: ['Python', 'Programming', 'Projects'], difficulty: 'Beginner', duration: '60 hours', category: 'Programming', language: 'hi', contentType: 'video' }
  ,{ title: 'JavaScript Tutorial Playlist in Hindi', provider: 'YouTube / CodeWithHarry', qualityScore: 0.82, sourceUrl: 'https://www.youtube.com/playlist?list=PLu0W_9lII9ahR1blWXxgSlL4y9iQBnLpR', instructor: 'CodeWithHarry', description: 'Hindi JavaScript playlist covering core language concepts and browser programming.', skills: ['JavaScript', 'Programming', 'Web Development'], difficulty: 'Beginner', duration: '25 hours', category: 'Web Development', language: 'hi', contentType: 'video' }
  ,{ title: 'Web Development Course in Hindi', provider: 'MyGreatLearning Academy', qualityScore: 0.78, sourceUrl: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/web-development-in-hindi', instructor: 'MyGreatLearning Academy', description: 'Free Hindi web development course for learners who prefer guided explanations in Hindi.', skills: ['HTML', 'CSS', 'JavaScript', 'Web Development'], difficulty: 'Beginner', duration: '8 hours', category: 'Web Development', language: 'hi', contentType: 'course' }
].map((course) => ({
  ...course,
  isFree: true,
  status: 'published',
  language: course.language || 'en',
  contentType: course.contentType || (course.provider.includes('YouTube') ? 'video' : 'course'),
  tags: ['free', 'public', ...(course.provider.includes('YouTube') ? ['youtube'] : [])]
}));

let catalogPromise;

async function ensureFreePublicCourses() {
  if (!catalogPromise) {
    catalogPromise = Promise.all(FREE_PUBLIC_COURSES.map((course) =>
      Course.updateOne({ sourceUrl: course.sourceUrl }, { $set: course }, { upsert: true, runValidators: true })
    )).catch((error) => {
      catalogPromise = null;
      throw error;
    });
  }
  await catalogPromise;
}

module.exports = { FREE_PUBLIC_COURSES, ensureFreePublicCourses };
